// Auto-generated by `supabase gen types typescript` (via Supabase MCP).
// Regenerate after every migration.
//
// NOTE: This is a copy of apps/web/src/lib/supabase/types.ts. Both files must
// be regenerated together. If we add a third consumer, extract into a shared
// @curi/db-types workspace package.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      artists: {
        Row: {
          flavors: string[];
          genres: string[];
          id: string;
          last_enriched_at: string | null;
          mb_tags: Json | null;
          musicbrainz_id: string | null;
          name: string;
          slug: string;
          subgenres: string[];
        };
        Insert: {
          flavors?: string[];
          genres?: string[];
          id?: string;
          last_enriched_at?: string | null;
          mb_tags?: Json | null;
          musicbrainz_id?: string | null;
          name: string;
          slug: string;
          subgenres?: string[];
        };
        Update: {
          flavors?: string[];
          genres?: string[];
          id?: string;
          last_enriched_at?: string | null;
          mb_tags?: Json | null;
          musicbrainz_id?: string | null;
          name?: string;
          slug?: string;
          subgenres?: string[];
        };
        Relationships: [];
      };
      event_artists: {
        Row: {
          artist_id: string;
          event_id: string;
          is_headliner: boolean;
          position: number;
        };
        Insert: {
          artist_id: string;
          event_id: string;
          is_headliner?: boolean;
          position?: number;
        };
        Update: {
          artist_id?: string;
          event_id?: string;
          is_headliner?: boolean;
          position?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'event_artists_artist_id_fkey';
            columns: ['artist_id'];
            isOneToOne: false;
            referencedRelation: 'artists';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'event_artists_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
        ];
      };
      events: {
        Row: {
          city: string;
          created_at: string;
          description: string | null;
          ends_at: string | null;
          flavors: string[];
          genres: string[];
          id: string;
          image_url: string | null;
          price_max: number | null;
          price_min: number | null;
          raw: Json | null;
          source: string;
          source_id: string;
          starts_at: string;
          ticket_url: string | null;
          title: string;
          updated_at: string;
          venue_id: string | null;
        };
        Insert: {
          city?: string;
          created_at?: string;
          description?: string | null;
          ends_at?: string | null;
          flavors?: string[];
          genres?: string[];
          id?: string;
          image_url?: string | null;
          price_max?: number | null;
          price_min?: number | null;
          raw?: Json | null;
          source: string;
          source_id: string;
          starts_at: string;
          ticket_url?: string | null;
          title: string;
          updated_at?: string;
          venue_id?: string | null;
        };
        Update: {
          city?: string;
          created_at?: string;
          description?: string | null;
          ends_at?: string | null;
          flavors?: string[];
          genres?: string[];
          id?: string;
          image_url?: string | null;
          price_max?: number | null;
          price_min?: number | null;
          raw?: Json | null;
          source?: string;
          source_id?: string;
          starts_at?: string;
          ticket_url?: string | null;
          title?: string;
          updated_at?: string;
          venue_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'events_venue_id_fkey';
            columns: ['venue_id'];
            isOneToOne: false;
            referencedRelation: 'venues';
            referencedColumns: ['id'];
          },
        ];
      };
      taxonomy_map: {
        Row: {
          flavors: string[];
          genres: string[];
          id: string;
          input_tag: string;
        };
        Insert: {
          flavors?: string[];
          genres?: string[];
          id?: string;
          input_tag: string;
        };
        Update: {
          flavors?: string[];
          genres?: string[];
          id?: string;
          input_tag?: string;
        };
        Relationships: [];
      };
      taxonomy_subgenres: {
        Row: {
          auto_created_at: string;
          confidence: number;
          flavors: string[];
          genres: string[];
          id: string;
          input_tag: string;
          parent_tag_id: string;
        };
        Insert: {
          auto_created_at?: string;
          confidence: number;
          flavors?: string[];
          genres?: string[];
          id?: string;
          input_tag: string;
          parent_tag_id: string;
        };
        Update: {
          auto_created_at?: string;
          confidence?: number;
          flavors?: string[];
          genres?: string[];
          id?: string;
          input_tag?: string;
          parent_tag_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'taxonomy_subgenres_parent_tag_id_fkey';
            columns: ['parent_tag_id'];
            isOneToOne: false;
            referencedRelation: 'taxonomy_map';
            referencedColumns: ['id'];
          },
        ];
      };
      user_saves: {
        Row: {
          created_at: string;
          event_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          event_id: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          event_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_saves_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
        ];
      };
      venues: {
        Row: {
          created_at: string;
          default_flavors: string[] | null;
          default_genres: string[] | null;
          id: string;
          lat: number | null;
          lng: number | null;
          name: string;
          neighborhood: string | null;
          slug: string;
          website: string | null;
        };
        Insert: {
          created_at?: string;
          default_flavors?: string[] | null;
          default_genres?: string[] | null;
          id?: string;
          lat?: number | null;
          lng?: number | null;
          name: string;
          neighborhood?: string | null;
          slug: string;
          website?: string | null;
        };
        Update: {
          created_at?: string;
          default_flavors?: string[] | null;
          default_genres?: string[] | null;
          id?: string;
          lat?: number | null;
          lng?: number | null;
          name?: string;
          neighborhood?: string | null;
          slug?: string;
          website?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
