// Auto-generated by `supabase gen types typescript` (via Supabase MCP).
// Regenerate after every migration.
//
// NOTE: This is a copy of apps/web/src/lib/supabase/types.ts. Both files must
// be regenerated together. If we add a third consumer, extract into a shared
// @curi/db-types workspace package.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      artists: {
        Row: {
          bandcamp_followers: number | null
          bandcamp_image_url: string | null
          bandcamp_url: string | null
          enrichment_confidence: string | null
          genres: string[]
          id: string
          last_enriched_at: string | null
          mb_tags: Json | null
          musicbrainz_id: string | null
          name: string
          popularity_checked_at: string | null
          popularity_discovery_failed_at: string | null
          slug: string
          soundcloud_followers: number | null
          soundcloud_image_url: string | null
          soundcloud_url: string | null
          soundcloud_username: string | null
          spotify_checked_at: string | null
          spotify_discovery_failed_at: string | null
          spotify_followers: number | null
          spotify_id: string | null
          spotify_image_url: string | null
          spotify_popularity: number | null
          spotify_url: string | null
          subgenres: string[]
          vibes: string[]
        }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      user_prefs: {
        Row: {
          calendar_opt_in: boolean
          created_at: string
          default_when: string | null
          digest_email: boolean
          location_opt_in: boolean
          notify_artist_drops: boolean
          onboarding_completed_at: string | null
          preferred_genres: string[]
          preferred_setting: string[]
          preferred_subgenres: string[]
          preferred_vibes: string[]
          soundcloud_last_synced_at: string | null
          soundcloud_username: string | null
          spotify_last_synced_at: string | null
          spotify_user_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      user_soundcloud_follows: {
        Row: {
          display_name: string | null
          followed_at: string | null
          soundcloud_username: string
          synced_at: string
          user_id: string
        }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      user_spotify_follows: {
        Row: {
          display_name: string | null
          followed_at: string | null
          spotify_artist_id: string
          synced_at: string
          user_id: string
        }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      events: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      event_artists: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      venues: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      profiles: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      taxonomy_map: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      taxonomy_subgenres: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      user_saves: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      artists_audit_backup: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      artists_sc_audit_2026_04_25: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
      events_audit_backup: {
        Row: { [k: string]: unknown }
        Insert: { [k: string]: unknown }
        Update: { [k: string]: unknown }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: { [k: string]: unknown }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
