'use client';

// Phase 6.3 v2 — typeahead dropdown for the global search bar.
//
// Anatomy (top → bottom):
//   Entity buttons   — "Show events with [Artist]" / "at [Venue]" if
//                      the top-scoring artist/venue matches >= 0.7
//                      (see ENTITY_THRESHOLD in lib/search.ts).
//   Events section   — up to 10 upcoming-event title matches.
//   Artists section  — up to 5 fuzzy-name matches; clicking sets ?artist=
//                      slug rather than navigating directly so the user
//                      stays on the feed with a filter applied.
//   Venues section   — up to 3 fuzzy-name matches; same filter behavior.
//   Empty state      — single-line copy when query has no hits.
//   Footer           — quiet "Press Enter to search" hint.
//
// Keyboard contract:
//   ArrowDown / ArrowUp   — move highlight (wraps top↔bottom).
//   Home / End            — jump to first / last suggestion.
//   Enter                 — activate highlighted row, or fall through
//                           to the parent's Enter handler if nothing's
//                           highlighted (the parent commits the raw
//                           ?q= query).
//   Escape                — close the popover (parent unmounts us).
// Hovered rows update aria-activedescendant so screen readers stay in
// sync with mouse-driven exploration.
//
// Avatar cascade:
//   Events → coalesce(event hero, venue photo) — already done in the
//            RPC. Renders the cascaded URL, or a tinted "?" if NULL.
//   Artists → coalesce(spotify, soundcloud, bandcamp). Renders the URL
//             or initials in a deterministic-tone circle.
//   Venues  → venues.image_url or NULL → tinted "V" placeholder.
//
// The popover uses `curi-glass` — keeps it visually consistent with
// the event cards, profile cards, and date picker.

import { useEffect, useMemo, useState } from 'react';
import { Calendar, MapPin, Mic2, Search, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import {
  AVATAR_BG,
  avatarToneFor,
  initialsFor,
  type AvatarTone,
} from '@/lib/avatars';
import type { SearchResultRow, SearchSuggestions as Suggestions } from '@/lib/search';

// One flat row in the keyboard nav order. Building this once per render
// from the bucketed Suggestions lets ArrowDown/ArrowUp walk a single
// list without caring which section the row belongs to.
type FlatRow = {
  /** Stable id used both for the React key and aria-activedescendant. */
  id: string;
  /** Activation handler — pushes the right URL for the row's kind. */
  activate: () => void;
  /** Discriminator so the highlight ring can color itself per kind. */
  kind: 'entity-artist' | 'entity-venue' | 'event' | 'artist' | 'venue';
};

export type SearchSuggestionsProps = {
  /** RPC result, already split into buckets. Pass null while loading
   *  the very first character; the component renders just the spinner. */
  data: Suggestions | null;
  /** Current search needle. Threaded in so the empty state and the
   *  "Press Enter to search [q]" footer can echo it back. */
  query: string;
  /** True while a fetch is in flight. Renders a small spinner inside
   *  the popover header so the user knows results may still arrive. */
  loading: boolean;
  /** Called with the activated row's URL. Parent merges it into the
   *  existing search params (so date/genre filters survive). */
  onSelect: (target: SelectTarget) => void;
  /** id of the listbox element. Generated by the parent (so the parent
   *  can wire `aria-controls` on the input that opens us) and applied
   *  to the popover root here. */
  listboxId: string;
  /** Notified whenever the keyboard / hover highlight changes — parent
   *  feeds this into `aria-activedescendant` on the input so screen
   *  readers announce the highlighted row. */
  onHighlightChange?: (id: string | null) => void;
  /** Forwarded ref to the root element so the parent can measure /
   *  outside-click against it. */
  rootRef?: React.RefObject<HTMLDivElement>;
  /** Imperative handle the parent uses to forward keydown events from
   *  the input. The parent owns focus on the input; we own the
   *  highlight state. */
  keyHandlerRef?: React.MutableRefObject<KeyHandler | null>;
};

export type SelectTarget =
  | { kind: 'event'; eventId: string }
  | { kind: 'artist'; slug: string }
  | { kind: 'venue'; slug: string };

export type KeyHandler = (e: React.KeyboardEvent<HTMLInputElement>) => boolean;

export function SearchSuggestions({
  data,
  query,
  loading,
  onSelect,
  listboxId,
  onHighlightChange,
  rootRef,
  keyHandlerRef,
}: SearchSuggestionsProps) {
  const [highlight, setHighlight] = useState<string | null>(null);

  // Mirror highlight state out to the parent so it can set
  // aria-activedescendant on the input. Skipping the prop's identity
  // dep is intentional — only the value matters.
  useEffect(() => {
    onHighlightChange?.(highlight);
  }, [highlight, onHighlightChange]);

  // Build the flat keyboard-walk order. Memoized on the data object
  // identity — the parent always swaps the whole `data` object on a
  // new fetch, so this is stable between keystrokes that didn't
  // produce new results.
  const rows = useMemo<FlatRow[]>(() => {
    if (!data) return [];
    const out: FlatRow[] = [];
    if (data.topArtist) {
      const a = data.topArtist;
      out.push({
        id: `entity-artist-${a.slug}`,
        kind: 'entity-artist',
        activate: () =>
          a.slug ? onSelect({ kind: 'artist', slug: a.slug }) : undefined,
      });
    }
    if (data.topVenue) {
      const v = data.topVenue;
      out.push({
        id: `entity-venue-${v.slug}`,
        kind: 'entity-venue',
        activate: () =>
          v.slug ? onSelect({ kind: 'venue', slug: v.slug }) : undefined,
      });
    }
    for (const e of data.events) {
      out.push({
        id: `event-${e.id}`,
        kind: 'event',
        activate: () => onSelect({ kind: 'event', eventId: e.id }),
      });
    }
    for (const a of data.artists) {
      out.push({
        id: `artist-${a.id}`,
        kind: 'artist',
        activate: () =>
          a.slug ? onSelect({ kind: 'artist', slug: a.slug }) : undefined,
      });
    }
    for (const v of data.venues) {
      out.push({
        id: `venue-${v.id}`,
        kind: 'venue',
        activate: () =>
          v.slug ? onSelect({ kind: 'venue', slug: v.slug }) : undefined,
      });
    }
    return out;
  }, [data, onSelect]);

  // Reset the highlight when the result set changes — otherwise the
  // ghost of a row that no longer exists keeps the highlight ring.
  useEffect(() => {
    if (rows.length === 0) {
      setHighlight(null);
      return;
    }
    if (!highlight || !rows.some((r) => r.id === highlight)) {
      setHighlight(rows[0]!.id);
    }
  }, [rows, highlight]);

  // Expose a key handler the parent can call from its <input>
  // onKeyDown. Returning true means "I handled this, prevent default"
  // — the parent uses that signal to call e.preventDefault().
  useEffect(() => {
    if (!keyHandlerRef) return;
    keyHandlerRef.current = (e) => {
      if (rows.length === 0) return false;
      const idx = highlight ? rows.findIndex((r) => r.id === highlight) : -1;
      if (e.key === 'ArrowDown') {
        const next = idx < 0 ? 0 : (idx + 1) % rows.length;
        setHighlight(rows[next]!.id);
        return true;
      }
      if (e.key === 'ArrowUp') {
        const next = idx <= 0 ? rows.length - 1 : idx - 1;
        setHighlight(rows[next]!.id);
        return true;
      }
      if (e.key === 'Home') {
        setHighlight(rows[0]!.id);
        return true;
      }
      if (e.key === 'End') {
        setHighlight(rows[rows.length - 1]!.id);
        return true;
      }
      if (e.key === 'Enter') {
        if (idx >= 0) {
          rows[idx]!.activate();
          return true;
        }
        return false; // let the parent commit ?q=
      }
      return false;
    };
    return () => {
      if (keyHandlerRef.current) keyHandlerRef.current = null;
    };
  }, [rows, highlight, keyHandlerRef]);

  const hasAnyResults =
    !!data &&
    (data.events.length > 0 ||
      data.artists.length > 0 ||
      data.venues.length > 0);

  return (
    <div
      ref={rootRef}
      role="listbox"
      id={listboxId}
      aria-label="Search suggestions"
      className={cn(
        // Solid dark panel — no backdrop-blur here. Glass blur works
        // over a predictable mono-chrome bg (e.g. bottom nav over the
        // page canvas) but smears colorful event card images when the
        // dropdown floats above the feed. A solid bg-base surface with
        // the canonical border + card shadow reads cleanly over anything.
        'absolute left-0 right-0 top-full z-50 mt-2',
        'overflow-hidden rounded-2xl shadow-card',
        'border border-white/[0.08]',
        'bg-bg-base',
        'animate-enter-up motion-reduce:animate-none',
      )}
    >
      {/* Header: tiny status row. Renders the spinner when fetching
          fresh results so the user knows new matches may still
          arrive — the existing rows underneath stay visible (no
          flash-of-empty) so the dropdown feels stable while typing. */}
      <div className="flex items-center justify-between gap-3 border-b border-white/[0.10] bg-bg-deep px-4 py-2">
        <div className="flex items-center gap-2 text-2xs text-fg-dim">
          <Search className="h-3 w-3" aria-hidden />
          <span className="tracking-tight" aria-live="polite" aria-atomic="true">
            {loading ? 'Searching…' : hasAnyResults ? 'Suggestions' : 'No matches'}
          </span>
        </div>
        {loading && (
          <Loader2
            className="h-3 w-3 animate-spin text-accent"
            aria-hidden
          />
        )}
      </div>

      <div className="max-h-[60vh] overflow-y-auto overscroll-contain">
        {/* Entity buttons */}
        {data?.topArtist?.slug && (
          <EntityButton
            id={`entity-artist-${data.topArtist.slug}`}
            kind="artist"
            highlighted={highlight === `entity-artist-${data.topArtist.slug}`}
            label={data.topArtist.title}
            onActivate={() =>
              onSelect({ kind: 'artist', slug: data.topArtist!.slug! })
            }
            onHover={setHighlight}
          />
        )}
        {data?.topVenue?.slug && (
          <EntityButton
            id={`entity-venue-${data.topVenue.slug}`}
            kind="venue"
            highlighted={highlight === `entity-venue-${data.topVenue.slug}`}
            label={data.topVenue.title}
            onActivate={() =>
              onSelect({ kind: 'venue', slug: data.topVenue!.slug! })
            }
            onHover={setHighlight}
          />
        )}

        {/* Events */}
        {data && data.events.length > 0 && (
          <Section title="Events" icon={<Calendar className="h-3 w-3" />}>
            {data.events.map((e) => {
              const id = `event-${e.id}`;
              return (
                <EventRow
                  key={id}
                  id={id}
                  row={e}
                  highlighted={highlight === id}
                  onActivate={() => onSelect({ kind: 'event', eventId: e.id })}
                  onHover={setHighlight}
                />
              );
            })}
          </Section>
        )}

        {/* Artists */}
        {data && data.artists.length > 0 && (
          <Section title="Artists" icon={<Mic2 className="h-3 w-3" />}>
            {data.artists.map((a) => {
              const id = `artist-${a.id}`;
              return (
                <ArtistRow
                  key={id}
                  id={id}
                  row={a}
                  highlighted={highlight === id}
                  onActivate={() =>
                    a.slug && onSelect({ kind: 'artist', slug: a.slug })
                  }
                  onHover={setHighlight}
                />
              );
            })}
          </Section>
        )}

        {/* Venues */}
        {data && data.venues.length > 0 && (
          <Section title="Venues" icon={<MapPin className="h-3 w-3" />}>
            {data.venues.map((v) => {
              const id = `venue-${v.id}`;
              return (
                <VenueRow
                  key={id}
                  id={id}
                  row={v}
                  highlighted={highlight === id}
                  onActivate={() =>
                    v.slug && onSelect({ kind: 'venue', slug: v.slug })
                  }
                  onHover={setHighlight}
                />
              );
            })}
          </Section>
        )}

        {/* Empty state — only show after the very first fetch resolves
            (data !== null) so we don't briefly render "no matches" on
            the initial keystroke. */}
        {data && !hasAnyResults && !loading && (
          <div className="flex flex-col items-center gap-2 px-4 py-8 text-center">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-white/[0.06]">
              <Search className="h-4 w-4 text-fg-dim" aria-hidden />
            </div>
            <p className="text-xs text-fg-muted">
              No matches for{' '}
              <span className="font-medium text-fg-primary">"{query}"</span>
            </p>
            <p className="text-2xs text-fg-dim">Try a different spelling or a broader term.</p>
          </div>
        )}
      </div>

      {/* Footer hint — only when we have a non-empty query so the bar
          doesn't add visual noise when the user just opens the input. */}
      {query.trim().length > 0 && (
        <div className="border-t border-white/[0.08] bg-bg-deep px-4 py-2 text-2xs text-fg-dim">
          Press{' '}
          <kbd className="rounded border border-white/[0.12] bg-white/[0.06] px-1.5 py-0.5 font-mono text-[10px] text-fg-primary">
            ↵
          </kbd>{' '}
          to search for{' '}
          <span className="font-medium text-fg-primary">"{query}"</span>
        </div>
      )}
    </div>
  );
}

// ── Subcomponents ─────────────────────────────────────────────────

function Section({
  title,
  icon,
  children,
}: {
  title: string;
  icon: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="border-t border-white/[0.10] first:border-t-0">
      <div className="flex items-center gap-1.5 px-4 py-1.5 text-2xs font-medium uppercase tracking-widest text-fg-dim">
        <span aria-hidden className="text-fg-muted">{icon}</span>
        {title}
      </div>
      <ul role="group" className="pb-1">
        {children}
      </ul>
    </div>
  );
}

function EntityButton({
  id,
  kind,
  label,
  highlighted,
  onActivate,
  onHover,
}: {
  id: string;
  kind: 'artist' | 'venue';
  label: string;
  highlighted: boolean;
  onActivate: () => void;
  onHover: (id: string) => void;
}) {
  // Tone matches the active-chip color the click eventually produces —
  // violet for artist, amber for venue — so the user can see the
  // upcoming chip color before they commit.
  const tone = kind === 'artist' ? 'violet' : 'amber';
  const toneClasses =
    tone === 'violet'
      ? 'border-violet/30 bg-violet/8 text-violet hover:bg-violet/12'
      : 'border-amber/30 bg-amber/8 text-amber hover:bg-amber/12';

  return (
    <button
      id={id}
      role="option"
      aria-selected={highlighted}
      type="button"
      tabIndex={-1}
      onMouseEnter={() => onHover(id)}
      onClick={onActivate}
      className={cn(
        'flex w-full cursor-pointer items-center gap-2.5 border-b border-white/[0.08] px-4 py-2.5 text-left text-xs transition-none',
        'border-l-2',
        'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-white/[0.20]',
        highlighted
          ? tone === 'violet'
            ? 'bg-violet/[0.12] border-l-violet'
            : 'bg-amber/[0.12] border-l-amber'
          : 'border-l-transparent hover:bg-white/[0.08]',
      )}
    >
      <span
        className={cn(
          'inline-flex items-center gap-1.5 rounded-pill border px-2.5 py-1 text-2xs font-medium',
          toneClasses,
        )}
      >
        {kind === 'artist' ? (
          <Mic2 className="h-3 w-3" aria-hidden />
        ) : (
          <MapPin className="h-3 w-3" aria-hidden />
        )}
        Show events {kind === 'artist' ? 'with' : 'at'}
      </span>
      <span className="truncate font-medium text-fg-primary">{label}</span>
    </button>
  );
}

function EventRow({
  id,
  row,
  highlighted,
  onActivate,
  onHover,
}: {
  id: string;
  row: SearchResultRow;
  highlighted: boolean;
  onActivate: () => void;
  onHover: (id: string) => void;
}) {
  const tone = avatarToneFor(row.title);
  return (
    <li>
      <button
        id={id}
        role="option"
        aria-selected={highlighted}
        type="button"
        tabIndex={-1}
        onMouseEnter={() => onHover(id)}
        onClick={onActivate}
        className={cn(
          'flex w-full cursor-pointer items-center gap-3 px-4 py-2.5 text-left transition-none',
          'border-l-2',
          'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-white/[0.20]',
          highlighted
            ? 'bg-accent/[0.12] border-l-accent'
            : 'border-l-transparent hover:bg-white/[0.08]',
        )}
      >
        <Thumb url={row.image_url} fallback={row.title} tone={tone} kind="event" />
        <div className="min-w-0 flex-1">
          <div className="truncate text-xs font-medium text-fg-primary">
            {row.title}
          </div>
          {row.subtitle && (
            <div className="truncate text-2xs text-fg-muted">
              {row.subtitle}
            </div>
          )}
        </div>
      </button>
    </li>
  );
}

function ArtistRow({
  id,
  row,
  highlighted,
  onActivate,
  onHover,
}: {
  id: string;
  row: SearchResultRow;
  highlighted: boolean;
  onActivate: () => void;
  onHover: (id: string) => void;
}) {
  const tone = avatarToneFor(row.title);
  return (
    <li>
      <button
        id={id}
        role="option"
        aria-selected={highlighted}
        type="button"
        tabIndex={-1}
        onMouseEnter={() => onHover(id)}
        onClick={onActivate}
        className={cn(
          'flex w-full cursor-pointer items-center gap-3 px-4 py-2.5 text-left transition-none',
          'border-l-2',
          'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-white/[0.20]',
          highlighted
            ? 'bg-violet/[0.12] border-l-violet'
            : 'border-l-transparent hover:bg-white/[0.08]',
        )}
      >
        <Thumb
          url={row.image_url}
          fallback={row.title}
          tone={tone}
          kind="artist"
        />
        <div className="min-w-0 flex-1">
          <div className="truncate text-xs font-medium text-fg-primary">
            {row.title}
          </div>
        </div>
      </button>
    </li>
  );
}

function VenueRow({
  id,
  row,
  highlighted,
  onActivate,
  onHover,
}: {
  id: string;
  row: SearchResultRow;
  highlighted: boolean;
  onActivate: () => void;
  onHover: (id: string) => void;
}) {
  return (
    <li>
      <button
        id={id}
        role="option"
        aria-selected={highlighted}
        type="button"
        tabIndex={-1}
        onMouseEnter={() => onHover(id)}
        onClick={onActivate}
        className={cn(
          'flex w-full cursor-pointer items-center gap-3 px-4 py-2.5 text-left transition-none',
          'border-l-2',
          'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-white/[0.20]',
          highlighted
            ? 'bg-amber/[0.12] border-l-amber'
            : 'border-l-transparent hover:bg-white/[0.08]',
        )}
      >
        <Thumb
          url={row.image_url}
          fallback={row.title}
          tone="amber"
          kind="venue"
        />
        <div className="min-w-0 flex-1">
          <div className="truncate text-xs font-medium text-fg-primary">
            {row.title}
          </div>
          {row.subtitle && (
            <div className="truncate text-2xs text-fg-muted">
              {row.subtitle}
            </div>
          )}
        </div>
      </button>
    </li>
  );
}

function Thumb({
  url,
  fallback,
  tone,
  kind,
}: {
  url: string | null;
  fallback: string;
  tone: AvatarTone;
  kind: 'event' | 'artist' | 'venue';
}) {
  // Slightly different shape per kind — circle for artists (matches the
  // EventCard avatar cluster), rounded square for events / venues.
  const shape = kind === 'artist' ? 'rounded-full' : 'rounded-lg';
  return (
    <div
      className={cn(
        'flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden border border-white/[0.12]',
        shape,
        !url && AVATAR_BG[tone],
        'font-display text-[11px] font-semibold',
      )}
      aria-hidden
    >
      {url ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={url}
          alt=""
          loading="lazy"
          className={cn(
            'h-full w-full object-cover',
            kind === 'artist' && 'object-top',
          )}
        />
      ) : (
        initialsFor(fallback)
      )}
    </div>
  );
}
